In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/168/Downloads/kmdb_csv.csv', encoding='cp949')
print(df.head())

   영화등록번호ID              영화등록번호NO                        영화명  \
F     27930        중요한 건 사랑한다는 거야  The Main Thing Is To Love
F     27931  에브리씽 유브 갓 하우 두 유 노우?                        NaN
F     27932                사랑과 죽음             Love And Death
F     27933     S.W.A.T.: 파이어 파이트       S.W.A.T.: Fire Fight
F     29853              스페이스 레인저                        NaN

                        영문제명    원제명   유형          용도           장르    제작국가  \
F  L'Important C'est D'Aimer    극영화  극장용       멜로드라마  이탈리아,프랑스,서독  1975.0
F                        NaN    극영화  극장용   코메디,멜로드라마           미국  2010.0
F             Love And Death    극영화  극장용         드라마           미국  1975.0
F       S.W.A.T.: Fire Fight    극영화  극장용          액션           미국  2011.0
F                   스페이스 레인저  TV-영화  TV용  액션,SF,어드벤처           미국  1993.0

                                                제작년도  ... 대표영화심의일 대표영화심의번호  \
F  Albina Productions S.a.r.l.,Rizzoli Film,TIT F...  ...     NaN      NaN
F                                                NaN  ...     NaN      NaN
F        Jack Rollins & Charles H. Joffe Productions  ...     NaN      NaN
F                                                NaN  ...     NaN      NaN
F                                                NaN  ...     NaN      NaN

  대표영화관람등급 대표개봉일 대표상영시간                              키워드  \
F      NaN   NaN  109.0  사진작가,에로영화,여배우,리처드3세,고리대금업자,삼각관계
F      NaN   NaN  121.0      소프트볼,국가대표,탈락,투수,중역,회계,부정,누명
F      NaN   NaN   85.0      유부녀,겁쟁이,나폴레옹,러시아,군입대,오페라,대포
F      NaN   NaN   88.0        동료,킬러,LA,경찰특공대,심리학자,인질,복수
F      NaN   NaN   45.0              우주평화,특공대,우주선,총격전,폭발

                                                 줄거리  KMDBURL  \
F  프랑스에서 만든 안드레이 줄랍스키 감독의 두번째 작품이자 그의 아버지가 쓴 소설을 ...      NaN
F  어린 시절부터 소프트볼에 매달려 살아온 리사는 국가 대표선수가 되는 것이 꿈. 그런...      NaN
F  사촌뻘 되는 유부녀 소냐를 사랑하는 청년 유부녀 보리스 그루센코(우디 알렌 분)은 ...      NaN
F  어제의 동료가 냉혈한 킬러로 돌아왔다! \r\n\r\n 로스앤젤리스 경찰 특공대(S...      NaN
F  제1부. '5인의 특공대'. 서기 2100년 은하계에서 가장 멀리 떨어진 호프기지 ...      NaN

                   최초등록일                  최종수정일
F  2011-05-03 17:01:49.0  2020-05-06 09:13:05.0
F  2011-05-03 17:09:36.0  2011-05-03 17:57:33.0
F  2011-05-03 17:31:46.0  2019-02-27 11:44:25.0
F  2011-05-03 18:02:13.0  2022-09-28 14:14:30.0
F  2012-06-20 16:32:47.0  2012-06-20 16:59:54.0

[5 rows x 25 columns]

C:\Users\168\AppData\Local\Temp\ipykernel_11816\3964315822.py:1: DtypeWarning: Columns (16,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/168/Downloads/kmdb_csv.csv', encoding='cp949')

In [3]:
df.reset_index(drop=True, inplace=False)

,영화등록번호ID,영화등록번호NO,영화명,영문제명,원제명,유형,용도,장르,제작국가,제작년도,...,대표영화심의일,대표영화심의번호,대표영화관람등급,대표개봉일,대표상영시간,키워드,줄거리,KMDBURL,최초등록일,최종수정일
0,27930,중요한 건 사랑한다는 거야,The Main Thing Is To Love,L'Important C'est D'Aimer,극영화,극장용,멜로드라마,"이탈리아,프랑스,서독",1975.0,"Albina Productions S.a.r.l.,Rizzoli Film,TIT F...",...,NaN,NaN,NaN,NaN,109.0,"사진작가,에로영화,여배우,리처드3세,고리대금업자,삼각관계",프랑스에서 만든 안드레이 줄랍스키 감독의 두번째 작품이자 그의 아버지가 쓴 소설을 ...,NaN,2011-05-03 17:01:49.0,2020-05-06 09:13:05.0
1,27931,에브리씽 유브 갓 하우 두 유 노우?,NaN,NaN,극영화,극장용,"코메디,멜로드라마",미국,2010.0,NaN,...,NaN,NaN,NaN,NaN,121.0,"소프트볼,국가대표,탈락,투수,중역,회계,부정,누명",어린 시절부터 소프트볼에 매달려 살아온 리사는 국가 대표선수가 되는 것이 꿈. 그런...,NaN,2011-05-03 17:09:36.0,2011-05-03 17:57:33.0
2,27932,사랑과 죽음,Love And Death,Love And Death,극영화,극장용,드라마,미국,1975.0,Jack Rollins & Charles H. Joffe Productions,...,NaN,NaN,NaN,NaN,85.0,"유부녀,겁쟁이,나폴레옹,러시아,군입대,오페라,대포",사촌뻘 되는 유부녀 소냐를 사랑하는 청년 유부녀 보리스 그루센코(우디 알렌 분)은 ...,NaN,2011-05-03 17:31:46.0,2019-02-27 11:44:25.0
3,27933,S.W.A.T.: 파이어 파이트,S.W.A.T.: Fire Fight,S.W.A.T.: Fire Fight,극영화,극장용,액션,미국,2011.0,NaN,...,NaN,NaN,NaN,NaN,88.0,"동료,킬러,LA,경찰특공대,심리학자,인질,복수",어제의 동료가 냉혈한 킬러로 돌아왔다! \r\n\r\n 로스앤젤리스 경찰 특공대(S...,NaN,2011-05-03 18:02:13.0,2022-09-28 14:14:30.0
4,29853,스페이스 레인저,NaN,스페이스 레인저,TV-영화,TV용,"액션,SF,어드벤처",미국,1993.0,NaN,...,NaN,NaN,NaN,NaN,45.0,"우주평화,특공대,우주선,총격전,폭발",제1부. '5인의 특공대'. 서기 2100년 은하계에서 가장 멀리 떨어진 호프기지 ...,NaN,2012-06-20 16:32:47.0,2012-06-20 16:59:54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,6016,한국여성 어제와 오늘,(Hangungnyeoseong eojewa oneul),NaN,교육물,-,NaN,대한민국,NaN,한국여성개발원,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-01-08 14:07:57.0,2014-01-08 14:10:28.0
99996,34019,트랜스페어런트,NaN,NaN,TV-시리즈,TV용,코메디,미국,2014.0,NaN,...,NaN,NaN,NaN,NaN,30.0,NaN,NaN,NaN,2015-01-12 16:22:51.0,2015-01-12 16:26:33.0
99997,36946,50만불의 대결,NaN,Perry Mason: The Case of the Lost Love,TV-영화,-,"드라마,범죄,미스터리",미국,1987.0,NaN,...,NaN,NaN,NaN,NaN,96.0,NaN,NaN,NaN,2016-11-09 14:37:05.0,2016-11-09 14:40:22.0
99998,26940,찰스턴 퍼레이드,NaN,Sur un air de Charleston,극영화,극장용,"드라마,판타지",프랑스,1927.0,Neo-Film,...,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,2010-09-10 10:38:37.0,2010-11-24 00:00:00.0
99999,887,배달의 기수(초병),(Baedarui gisu(chobyeong)),NaN,광고홍보물,극장용,군사,대한민국,1976.0,국군홍보관리소,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1900-01-01 00:00:00.0,2022-06-07 08:04:40.0

In [4]:
df.columns

Index(['영화등록번호ID', '영화등록번호NO', '영화명', '영문제명', '원제명', '유형', '용도', '장르', '제작국가',
       '제작년도', '제작사', '감독', '각본', '출연', '영화심의여부', '대표영화심의일', '대표영화심의번호',
       '대표영화관람등급', '대표개봉일', '대표상영시간', '키워드', '줄거리', 'KMDBURL', '최초등록일',
       '최종수정일'],
      dtype='object')

In [5]:
df.describe()

,영화등록번호ID,제작국가,대표영화관람등급,대표개봉일,대표상영시간,KMDBURL
count,100000.000000,95646.000000,0.0,2.246700e+04,87736.000000,0.0
mean,22594.964000,1999.474855,NaN,1.997689e+07,66.691142,NaN
std,16778.819732,22.099115,NaN,8.557508e+05,52.568833,NaN
min,1.000000,1885.000000,NaN,0.000000e+00,1.000000,NaN
25%,7499.000000,1988.000000,NaN,1.990093e+07,19.000000,NaN
50%,21125.500000,2007.000000,NaN,2.008102e+07,76.000000,NaN
75%,34087.250000,2017.000000,NaN,2.017022e+07,97.000000,NaN
max,59157.000000,2024.000000,NaN,2.023110e+07,3180.000000,NaN

In [7]:
df['제작국가'].value_counts()

2019.0    4394
2020.0    4362
2017.0    4145
2021.0    4112
2018.0    3997
          ...
1897.0      11
2024.0       2
1893.0       2
1885.0       1
1887.0       1
Name: 제작국가, Length: 134, dtype: int64

In [8]:
df.isnull().sum(axis=0)

영화등록번호ID         0
영화등록번호NO         0
영화명          19388
영문제명         59062
원제명              0
유형           10271
용도           14813
장르            2685
제작국가          4354
제작년도         38111
제작사          10125
감독           29388
각본           51494
출연           29388
영화심의여부       52465
대표영화심의일      62898
대표영화심의번호     63367
대표영화관람등급    100000
대표개봉일        77533
대표상영시간       12264
키워드          60552
줄거리          20181
KMDBURL     100000
최초등록일         6423
최종수정일            0
dtype: int64

In [9]:
df.isnull().sum(axis=1)

F     6
F     9
F     6
F     7
F     9
     ..
A    16
F    12
F    10
F     9
A    14
Length: 100000, dtype: int64

In [11]:
df.columns['영화명', '장르', '제작국가', '제작년도', '제작사', '감독', '각본', '출연',  '대표개봉일', '대표상영시간', '줄거리']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [13]:
dataFrame = df[['영화명', '장르', '제작국가', '제작년도', '제작사', '감독', '각본', '출연',  '대표개봉일', '대표상영시간', '줄거리']]

In [16]:
dataFrame.isnull().sum(axis=0)

영화명       19388
장르         2685
제작국가       4354
제작년도      38111
제작사       10125
감독        29388
각본        51494
출연        29388
대표개봉일     77533
대표상영시간    12264
줄거리       20181
dtype: int64

In [17]:
dataFrame.dropna(axis=0)

,영화명,장르,제작국가,제작년도,제작사,감독,각본,출연,대표개봉일,대표상영시간,줄거리
F,The Collector,미국,2009.0,"LD Entertainment,Fortress Features,Imaginarium...",마커스 던스탄,"조시 스튜어트,마이클 레일리 버크,안드리아 로스,후안 페르난데즈,카리 스콧 콜린스 ...","마커스 던스탄,패트릭 멜튼","조시 스튜어트,마이클 레일리 버크,안드리아 로스,후안 페르난데즈,카리 스콧 콜린스 ...",20110526.0,90.0,마스크 뒤에 감춰진 공포 트랩 | 놈은 반드시 한 명만 수집한다!\r\n\r\n새로...
A,(Nangmandakteo iyeongmanui mojeong),대한민국,2022.0,시네마테크 충무로,김문옥,"이영만(이영만 원장),손민지(영만 모),이자은(리포터/시낭송/해설),박효근(편집장)...",김문옥,"이영만(이영만 원장),손민지(영만 모),이자은(리포터/시낭송/해설),박효근(편집장)...",20221026.0,101.0,다양한 분야에서 활동 중인 치의학박사 이영만의 자전적 삶을 그린 그린 다큐멘터리 영화
F,X-Men: First Class,미국,2011.0,Bad Hat Harry Productions,매튜 본,"제임스 맥어보이,마이클 파스벤더,케빈 베이컨,니콜라스 홀트,제이슨 플레밍,루카스 틸...","제인 골드먼,애쉴리 밀러,제이미 모스,조쉬 슈와츠","제임스 맥어보이,마이클 파스벤더,케빈 베이컨,니콜라스 홀트,제이슨 플레밍,루카스 틸...",20110602.0,132.0,찰스 자비에와 에릭 랜셔가 각각 ‘프로페서 X’와 ‘매그니토’라는 이름을 얻기 전 ...
F,SKILLS,스웨덴,2011.0,Timelock Film,요하네스 루네보그,"조세핀 알,칼 엔더슨",토마스 암뢰브,"조세핀 알,칼 엔더슨",20110604.0,85.0,어느날 경찰인 아버지가 프랭크라는 불법 지하게임업자에게 총을 맞고 부상을 당하게 되...
F,The War with Grandpa,미국,2020.0,Marro Films,팀 힐,"로버트 드 니로(에드),우마 서먼(샐리),오크스 페글리(피터),롭 리글(아서),제인...","리사 애드다리오,톰 J. 애스틀,매트 엠버","로버트 드 니로(에드),우마 서먼(샐리),오크스 페글리(피터),롭 리글(아서),제인...",20210224.0,98.0,할아버지 ‘에드’에게 방을 뺏겨 다락방 신세가 된 손자 ‘피터’.\r\n방을 되찾기...
...,...,...,...,...,...,...,...,...,...,...,...
F,The Way of the Househusband: The Cinema,일본,2022.0,파인 엔터테인먼트,루토 토이치로,"타마키 히로시(타츠),카와구치 하루나(미쿠),시손 쥰(마사),후루카와 유타(사카이 ...","우다 마나부,루토 토이치로","타마키 히로시(타츠),카와구치 하루나(미쿠),시손 쥰(마사),후루카와 유타(사카이 ...",20230616.0,118.0,전국을 주름 잡던 야쿠자 '타츠'. '미쿠'를 만나 결혼하면서 야쿠자 생활을 청산하...
K,I Am Here (Naneun yeogie itda),대한민국,2022.0,㈜미학인우주선,신근호,"조한선(김선두),정진운(김규종),정태우(김영조),노수산나(신아승),박순천(한영해),...",신근호(신근호),"조한선(김선두),정진운(김규종),정태우(김영조),노수산나(신아승),박순천(한영해),...",20230412.0,82.0,"과거, 살인자를 검거하는 과정에서 칼에 폐를 찔린 후 장기 이식을 통해 기적적으로 ..."
F,Pinocchio: A True Story,"러시아,헝가리",2021.0,"Luminescence,Licensing Brands",바실리 로벤스키,"김다올(피노키오 한국어 목소리),정성원(제페토 한국어 목소리),박시윤(벨라 한국어 ...","바실리 로벤스키,막심 스베시니코프,바딤 스베시니코프","김다올(피노키오 한국어 목소리),정성원(제페토 한국어 목소리),박시윤(벨라 한국어 ...",20230713.0,84.0,외로이 살던 제페토 할아버지가 남자아이 모습의 나무 인형을 만들고 피노키오라는 이름...
K,Our Song (Geu norae),대한민국,2023.0,"스토리 플레이,SG엔터테인먼트(주)",오성수,"오진석(요셉),한기찬(청명),조정환(호석),유혜인(청아),류화영(선아),박현정(현숙...",오성수(이지영),"오진석(요셉),한기찬(청명),조정환(호석),유혜인(청아),류화영(선아),박현정(현숙...",20230816.0,117.0,아무 것도 가진 것 없는 스무살의 요셉 앞에 기적과 같은 노래가 하나 뚝 떨어진다....
A,"JAURIM, The Wonderland",대한민국,2023.0,"써티세븐스디그리(주),러브마뉴버","김지환,허민","김윤아(본인),이선규(본인),김진만(본인),임진모(Interview),배순탁(Int...",손희송,"김윤아(본인),이선규(본인),김진만(본인),임진모(Interview),배순탁(Int...",20230607.0,79.0,대한민국 최고의 밴드 자우림은 데뷔 25주년을 맞이하여 117명의 팬들이 코러스로 ...

In [18]:
dataFrame.describe()

               제작국가         대표개봉일        대표상영시간
count  95646.000000  2.246700e+04  87736.000000
mean    1999.474855  1.997689e+07     66.691142
std       22.099115  8.557508e+05     52.568833
min     1885.000000  0.000000e+00      1.000000
25%     1988.000000  1.990093e+07     19.000000
50%     2007.000000  2.008102e+07     76.000000
75%     2017.000000  2.017022e+07     97.000000
max     2024.000000  2.023110e+07   3180.000000

In [21]:
dataFrame['영화명'].value_counts()

Nippon News, Nihon News                   69
Bakgeunja                                 37
Asahi News                                34
.                                         26
Summer Time Rendering                     25
                                          ..
National Glory Church (Gukgwanggyohoe)     1
(Gaemiwa bejjangi)                         1
Angel (Cheonsaga doeryeomyeon)             1
Mrs. Immoral                               1
(Baedarui gisu(chobyeong))                 1
Name: 영화명, Length: 75943, dtype: int64

In [22]:
dataFrame['장르'].value_counts()

대한민국                          43139
미국                            18504
일본                             9791
프랑스                            2659
영국                             2253
                              ...
이탈리아,미국,홍콩                        1
멕시코,이탈리아,홍콩                       1
말레이시아,필리핀                         1
터키,프랑스,불가리아,독일,보스니아-헤르체고비나        1
노르웨이,덴마크,영국                       1
Name: 장르, Length: 2708, dtype: int64

2019.0    4394
2020.0    4362
2017.0    4145
2021.0    4112
2018.0    3997
          ...
1897.0      11
2024.0       2
1893.0       2
1885.0       1
1887.0       1
Name: 제작국가, Length: 134, dtype: int64

에스티에스엔터테인먼트                                         1199
한국영화아카데미                                             996
센츄리 픽쳐스                                              964
국군홍보관리소                                              893
국립영화제작소                                              798
                                                    ...
Finnkino,Megamania                                     1
Les Productions du Tr?sor,EuropaCorp,Caneo Films       1
Indigo Film,Medusa Film                                1
Ink Factory, The,Potboiler Productions                 1
Neo-Film                                               1
Name: 제작년도, Length: 27613, dtype: int64

In [25]:
dataFrame['제작사'].value_counts()

코지마 유키오                        463
니시다 류지                         229
스즈키 켄이치로                       165
조르쥬 멜리에스                       154
김수용                            128
                              ...
반비노                              1
크리스토퍼 모라핸                        1
David Bilcock,Robin Copping      1
Jim Sotos                        1
질 솔로웨이                           1
Name: 제작사, Length: 39748, dtype: int64

In [26]:
dataFrame['감독'].value_counts()

카와카미 나나미                                          36
하타노 유이                                            35
카자마 유미                                            28
아라시                                               24
쇼다 치사토                                            24
                                                  ..
존 쿠삭,조안 쿠삭,마리사 토메이,힐러리 더프,벤 킹슬리,댄 애크로이드,네드 벨러미     1
레이 발렌틴,데이빗 크렌,리리 보단                                1
채닝 테이텀,이병헌,브루스 윌리스,더 락,레이 스티븐슨,애드리앤 팰릭키 ,레이 파크     1
브래들리 쿠퍼,애비 코니쉬,로버트 드 니로,앤드류 하워드,안나 프리엘,조니 위트워스     1
까트린 헤스링,쟈니 허긴스,장 르누아르,피에르 브라윈베르쥐                   1
Name: 감독, Length: 66783, dtype: int64

In [27]:
dataFrame['각본'].value_counts()

신봉승                                   91
윤삼육                                   79
곽일로                                   69
이희우                                   67
김하림                                   60
                                      ..
최정미                                    1
피어스 애쉬워스,닉 무어크로프트                      1
사이몬 스톤                                 1
유한철,임권택                                1
Erle Stanley Gardner,Dean Hargrove     1
Name: 각본, Length: 32875, dtype: int64

In [28]:
dataFrame['출연'].value_counts()

카와카미 나나미                                          36
하타노 유이                                            35
카자마 유미                                            28
아라시                                               24
쇼다 치사토                                            24
                                                  ..
존 쿠삭,조안 쿠삭,마리사 토메이,힐러리 더프,벤 킹슬리,댄 애크로이드,네드 벨러미     1
레이 발렌틴,데이빗 크렌,리리 보단                                1
채닝 테이텀,이병헌,브루스 윌리스,더 락,레이 스티븐슨,애드리앤 팰릭키 ,레이 파크     1
브래들리 쿠퍼,애비 코니쉬,로버트 드 니로,앤드류 하워드,안나 프리엘,조니 위트워스     1
까트린 헤스링,쟈니 허긴스,장 르누아르,피에르 브라윈베르쥐                   1
Name: 출연, Length: 66783, dtype: int64

In [6]:

df_drop_row = csv_data_df[['영화등록번호ID', '영화등록번호NO', '영화명', '영문제명', '원제명', '유형', '용도', '장르', '제작국가',
       '제작년도', '제작사', '감독', '각본', '출연', '영화심의여부', '대표영화심의일', '대표영화심의번호',
       '대표영화관람등급', '대표개봉일', '대표상영시간', '키워드', '줄거리', 'KMDBURL', '최초등록일',
       '최종수정일']].dropna(axis=0)

In [8]:
df_drop_row = csv_data_df[['영화등록번호ID', '영화등록번호NO', '영화명', '영문제명', '원제명', '유형', '용도', '장르', '제작국가',
       '제작년도', '제작사', '감독', '각본', '출연', '영화심의여부', '대표영화심의일', '대표영화심의번호',
       '대표영화관람등급', '대표개봉일', '대표상영시간', '키워드', '줄거리', 'KMDBURL', '최초등록일',
       '최종수정일']].dropna(axis=1)

In [9]:
df_drop_row.shape

(100000, 4)

In [10]:
df_drop_row.value_counts()

영화등록번호ID  영화등록번호NO                  원제명       최종수정일
7596      NHK 지구대기행                 TV-다큐멘터리  2019-07-17 11:23:41.0    8
10212     Archives Korea 1930-1940  기록물       2023-04-03 11:49:30.0    5
6587      조선과 만주                    다큐멘터리     2022-09-30 10:26:11.0    4
4519      분노의 뉴올리언스                 TV-다큐멘터리  2019-07-30 09:40:05.0    4
9530      니혼 뉴스, 조선인학교사건            정보물       2022-05-10 17:40:43.0    4
                                                                      ..
10149     7인의 초인과 괴물 F              극영화       2016-02-17 16:28:25.0    1
          11X14                     다큐멘터리     2019-12-13 14:05:55.0    1
10148     소피와 수진 사이                 다큐멘터리     2021-11-09 14:41:12.0    1
          김추자 : 무인도                 극영화       2020-08-10 10:01:33.0    1
59157     레트로 벤전스                   극영화       2023-07-25 10:58:02.0    1
Length: 98976, dtype: int64